#+AUTHOR: jotix
#+TITLE: JOTIX NixOS & Linux Notes
#+DESCRIPTION: jotix's notes for configuring and tweaking in linux.
#+STARTUP: show2levels

* Table of Contents :TOC:
- [[#arch-linux][Arch Linux]]
- [[#nixos][NixOS]]
  - [[#installation][Installation]]
  - [[#module-template][Module Template]]
  - [[#virtiofs][virtiofs]]
  - [[#plasma-packages][Plasma packages]]
- [[#gnu-guix][Gnu-Guix]]
- [[#general-notes][General Notes]]
  - [[#impresora-brother-hl-1212w-connection][impresora Brother HL-1212W connection]]
  - [[#youtube-ublock-shorts-filter][YouTube uBlock shorts filter]]
  - [[#launch-a-virtual-monitor-with-kwin_wayland][Launch a virtual monitor with kwin_wayland]]
  - [[#dd-iso-file-in-usb-device][dd iso file in USB device]]
  - [[#creating-7z-encypted-file][creating 7z encypted file]]
  - [[#ip-camera-as-webcam][IP camera as webcam]]

* Arch Linux

Clone this repo and execute the installer.

#+begin_src sh
pacman -Sy git
git clone http://github.com/jotix/jotix-config.git
cd jotix-config/scripts/arch-install
./arch-install.sh
#+end_src

* NixOS

** Installation

Download the install script

#+begin_src sh
curl -o nixos-install.sh https://raw.githubusercontent.com/jotix/jotix-config/refs/heads/main/scripts/nixos-install.sh
#+end_src

Make the script executable & run it

#+begin_src sh
chmod +x nixos-install.sh
./nixos-install.sh
#+end_src

** Module Template

#+begin_src nix
### NAME Module

{ config, lib, pkgs, ... }:

{
  options.OPTION.enable = lib.mkEnableOption "Enable OPTION";
  
  config = lib.mkIf(config.OPTION.enable) {
    
  };
}
#+end_src

** virtiofs

Error starting domain: operation failed: Unable to find a satisfying virtiofsd

add virtiofsd into your systemPackages and add following into virt-manager filesystem xml:

#+begin_src html
<binary path="/run/current-system/sw/bin/virtiofsd"/>
#+end_src

** Plasma packages

paquetes que recopile tratando de hacer funcionar
las cuentas online (google drive)
pero nada funciona hasta ahora

#+begin_src nix
[
  libsForQt5.plasma-browser-integration
  libsForQt5.kaccounts-integration
  libsForQt5.kaccounts-providers
  libsForQt5.kio-gdrive
  libsForQt5.signond
  libsForQt5.qoauth
  libsForQt5.accounts-qt
  libsForQt5.mauikit-accounts
] ++ (with lib; filter isDerivation (attrValues pkgs.plasma5Packages.kdeGear)); ## for install all kde apps
#+end_src

* Gnu-Guix
Now we can start the system installation!

First we need to set up the Guix build daemon
to target the new system partition by running
this command:

#+begin_src sh
herd start cow-store /mnt
#+end_src

We also want to save the channel configuration
that was used to produce the installer image onto
our new machine, so we will copy it over now:

#+begin_src sh
cp /etc/channels.scm /mnt/etc/
chmod +w /mnt/etc/channels.scm
#+end_src

The following command will install your system configuration
using the included channels.scm file so that you get both
the main Guix channel and the Nonguix channel which contains
the full Linux kernel:

#+begin_src sh
sudo guix archive --authorize < signing-key.pub
guix time-machine -C ./channels.scm -- system init ./config.scm /mnt --substitute-urls='https://ci.guix.gnu.org https://bordeaux.guix.gnu.org https://substitutes.nonguix.org'
#+end_src

This command uses the channel defined in clannels.scm and the substitutes for nonguix alternatively run the script wich contains the last command

#+begin_src sh
./install.sh
#+end_src

* General Notes

** impresora Brother HL-1212W connection

*** KDE

edit the connection in the setting panel
ipp://192.168.0.7/ipp/port1

*** Manual config

For network printers, use ipp://printer_ip/ipp/port1 as printer address.
cambiar la direccion de la impresora en el gui del DE por la indicada arriba usando la IP de la impresora, (192.168.0.7)

#+begin_src sh
sudo vim /etc/cups/printers.conf
#+end_src

In a terminal:

#+begin_src sh
sudo systemctl stop cups
sudo vi /etc/cups/printers.conf - (or the text editor of your choice, I chose vi.)

locate the printer's URI (in bold below), it will be among all of your printers' profiles, they are arranged within tags like:

<Printer My Poop Laser Printer>
PrinterId 1
UUID urn:uuid:c41ca0c7-52f3-3448-5dfe-11281fc3ac2e
AuthInfoRequired none
Info
Location
MakeModel Generic IPP Everywhere Printer
DeviceURI ipp://192.168.200.2/printers/laser
State Idle
.
.
</Printer>

You can edit the IP there, save it.
And then restart cups...

sudo systemctl restart cups
#+end_src  

** YouTube uBlock shorts filter

#+begin_src sh
! Title: Hide YouTube Shorts
! Description: Hide all traces of YouTube shorts videos on YouTube
! Version: 1.8.0
! Last modified: 2023-01-08 20:02
! Expires: 2 weeks (update frequency)
! Homepage: https://github.com/gijsdev/ublock-hide-yt-shorts
! License: https://github.com/gijsdev/ublock-hide-yt-shorts/blob/master/LICENSE.md

! Hide all videos containing the phrase "#shorts"
youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(#shorts))
youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(#Shorts))
youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(#short))
youtube.com##ytd-grid-video-renderer:has(#video-title:has-text(#Short))

! Hide all videos with the shorts indicator on the thumbnail
youtube.com##ytd-grid-video-renderer:has([overlay-style="SHORTS"])
youtube.com##ytd-rich-item-renderer:has([overlay-style="SHORTS"])
youtube.com##ytd-video-renderer:has([overlay-style="SHORTS"])
youtube.com##ytd-item-section-renderer.ytd-section-list-renderer[page-subtype="subscriptions"]:has(ytd-video-renderer:has([overlay-style="SHORTS"]))

! Hide shorts button in sidebar
youtube.com##ytd-guide-entry-renderer:has-text(Shorts)
youtube.com##ytd-mini-guide-entry-renderer:has-text(Shorts)

! Hide shorts section on homepage
youtube.com##ytd-rich-section-renderer:has(#rich-shelf-header:has-text(Shorts))
youtube.com##ytd-reel-shelf-renderer:has(.ytd-reel-shelf-renderer:has-text(Shorts))

! Hide shorts tab on channel pages
! Old style
youtube.com##tp-yt-paper-tab:has(.tp-yt-paper-tab:has-text(Shorts))
! New style (2023-10)
youtube.com##yt-tab-shape:has-text(/^Shorts$/)

! Hide shorts in video descriptions
youtube.com##ytd-reel-shelf-renderer.ytd-structured-description-content-renderer:has-text("Shorts remixing this video")

! Remove empty spaces in grid
youtube.com##ytd-rich-grid-row,#contents.ytd-rich-grid-row:style(display: contents !important)


!!! MOBILE !!!

! Hide all videos in home feed containing the phrase "#shorts"
m.youtube.com##ytm-rich-item-renderer:has(#video-title:has-text(#shorts))
m.youtube.com##ytm-rich-item-renderer:has(#video-title:has-text(#Shorts))
m.youtube.com##ytm-rich-item-renderer:has(#video-title:has-text(#short))
m.youtube.com##ytm-rich-item-renderer:has(#video-title:has-text(#Short))

! Hide all videos in subscription feed containing the phrase "#shorts"
m.youtube.com##ytm-item-section-renderer:has(#video-title:has-text(#shorts))
m.youtube.com##ytm-item-section-renderer:has(#video-title:has-text(#Shorts))
m.youtube.com##ytm-item-section-renderer:has(#video-title:has-text(#short))
m.youtube.com##ytm-item-section-renderer:has(#video-title:has-text(#Short))

! Hide shorts button in the bottom navigation bar
m.youtube.com##ytm-pivot-bar-item-renderer:has(.pivot-shorts)

! Hide all videos with the shorts indicator on the thumbnail
m.youtube.com##ytm-video-with-context-renderer:has([data-style="SHORTS"])

! Hide shorts sections
m.youtube.com##ytm-rich-section-renderer:has(ytm-reel-shelf-renderer:has(.reel-shelf-title-wrapper:has-text(Shorts)))
m.youtube.com##ytm-reel-shelf-renderer.item:has(.reel-shelf-title-wrapper:has-text(Shorts))

! Hide shorts tab on channel pages
m.youtube.com##.single-column-browse-results-tabs>a:has-text(Shorts)
#+end_src

** Launch a virtual monitor with kwin_wayland

#+begin_src sh
export $(dbus-launch); kwin_wayland -s "wayland-1" --xwayland plasmashell
#+end_src

** dd iso file in USB device

#+begin_src sh
dd bs=4M if=path/to/archlinux-version-x86_64.iso of=/dev/disk/by-id/usb-My_flash_drive conv=fsync oflag=direct status=progress
#+end_src

** creating 7z encypted file

#+begin_src sh
s7z a \
   -t7z -m0=lzma2 -mx=9 -mfb=64 \
   -md=32m -ms=on -mhe=on -p'eat_my_shorts' \
   archive.7z dir1
#+end_src
 
** IP camera as webcam

#+begin_src sh
sudo modprobe v4l2loopbak-dkms
#+end_src

